version: '2'
services:
  beat:
    build: .
    environment:
      - LIBBEAT_PATH=/go/src/github.com/wangjia184/beats/libbeat
      # Puts build dir outside of shared file system to prevent issues
      # This means artifacts are not shared locally
      - BUILD_DIR=/tmp/build
    volumes:
      - ..:/go/src/github.com/wangjia184/beats/
    working_dir: /go/src/github.com/wangjia184/beats/packetbeat
