version: '2.3'
services:
  beat:
    build: ../../auditbeat
    working_dir: /go/src/github.com/wangjia184/beats/x-pack/auditbeat
    volumes:
      - ${PWD}/../..:/go/src/github.com/wangjia184/beats/
    command: make
    privileged: true
    pid: host
    cap_add:
      - AUDIT_CONTROL
      - AUDIT_READ
