version: '2.3'
services:
  beat:
    build: ../../metricbeat
    environment:
      - TEST_ENVIRONMENT=false
    working_dir: /go/src/github.com/wangjia184/beats/x-pack/metricbeat
    volumes:
      - ${PWD}/../..:/go/src/github.com/wangjia184/beats/
      - /var/run/docker.sock:/var/run/docker.sock
    command: make
    env_file:
      - ./module/mssql/_meta/env

  # Modules
  mssql:
    build: ./module/mssql/_meta
